# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/system_ila_3_0.xci
# IP: The module: 'system_ila_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/system_ila_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/system_ila_3_0.xci
# IP: The module: 'system_ila_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/MyFiles/EGo1_HDB3_and_BPSK/vivado_proj/DMA/dma.srcs/sources_1/bd/system/ip/system_ila_3_0/system_ila_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
