# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/Microblaze/Microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze || ORIG_REF_NAME==Microblaze} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_microblaze_0_0/Microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_microblaze_0_0 || ORIG_REF_NAME==Microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_axi_gpio_0_0/Microblaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_axi_gpio_0_0 || ORIG_REF_NAME==Microblaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_axi_uartlite_0_0/Microblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==Microblaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_xadc_wiz_0_0/Microblaze_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xadc_wiz_0_0 || ORIG_REF_NAME==Microblaze_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_microblaze_0_axi_periph_0/Microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_microblaze_0_axi_intc_0/Microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Microblaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_microblaze_0_xlconcat_0/Microblaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Microblaze_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_mdm_1_1/Microblaze_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_mdm_1_1 || ORIG_REF_NAME==Microblaze_mdm_1_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_clk_wiz_1_1/Microblaze_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_clk_wiz_1_1 || ORIG_REF_NAME==Microblaze_clk_wiz_1_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_rst_clk_wiz_1_100M_1/Microblaze_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Microblaze_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_sdk_vga4_dis_included_0_0/Microblaze_sdk_vga4_dis_included_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_sdk_vga4_dis_included_0_0 || ORIG_REF_NAME==Microblaze_sdk_vga4_dis_included_0_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_xbar_0/Microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xbar_0 || ORIG_REF_NAME==Microblaze_xbar_0} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_dlmb_v10_1/Microblaze_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_dlmb_v10_1 || ORIG_REF_NAME==Microblaze_dlmb_v10_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_ilmb_v10_1/Microblaze_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_ilmb_v10_1 || ORIG_REF_NAME==Microblaze_ilmb_v10_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_dlmb_bram_if_cntlr_1/Microblaze_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Microblaze_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_ilmb_bram_if_cntlr_1/Microblaze_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Microblaze_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_lmb_bram_1/Microblaze_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_lmb_bram_1 || ORIG_REF_NAME==Microblaze_lmb_bram_1} -quiet] -quiet

# IP: bd/Microblaze/ip/Microblaze_axi_timer_0_0/Microblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_axi_timer_0_0 || ORIG_REF_NAME==Microblaze_axi_timer_0_0} -quiet] -quiet

# XDC: bd/Microblaze/Microblaze_ooc.xdc
