# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.cache/wt [current_project]
set_property parent.project_path D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/vivado/sdk_vga_test6_fuben2/sdk_vga4_dis_included_1.0/sdk_vga4_dis_included_1.0 [current_project]
set_property ip_output_repo d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/hdl/Microblaze_wrapper.v
add_files D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/Microblaze.bd
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_0/Microblaze_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_0/Microblaze_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_0/Microblaze_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_gpio_0_0/Microblaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_gpio_0_0/Microblaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_gpio_0_0/Microblaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_uartlite_0_0/Microblaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_uartlite_0_0/Microblaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_uartlite_0_0/Microblaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_xadc_wiz_0_0/Microblaze_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_xadc_wiz_0_0/Microblaze_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_axi_intc_0/Microblaze_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_axi_intc_0/Microblaze_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_microblaze_0_axi_intc_0/Microblaze_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_mdm_1_1/Microblaze_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_mdm_1_1/Microblaze_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_clk_wiz_1_1/Microblaze_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_clk_wiz_1_1/Microblaze_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_clk_wiz_1_1/Microblaze_clk_wiz_1_1_late.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_clk_wiz_1_1/Microblaze_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_rst_clk_wiz_1_100M_1/Microblaze_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_rst_clk_wiz_1_100M_1/Microblaze_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_rst_clk_wiz_1_100M_1/Microblaze_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_xbar_0/Microblaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_dlmb_v10_1/Microblaze_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_dlmb_v10_1/Microblaze_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_ilmb_v10_1/Microblaze_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_ilmb_v10_1/Microblaze_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_dlmb_bram_if_cntlr_1/Microblaze_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_ilmb_bram_if_cntlr_1/Microblaze_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_lmb_bram_1/Microblaze_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_timer_0_0/Microblaze_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/ip/Microblaze_axi_timer_0_0/Microblaze_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/sources_1/bd/Microblaze/Microblaze_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files D:/vivado/sdk_vga_test6_fuben2/sdk_vga_test6_fuben2.srcs/constrs_1/new/xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Microblaze_wrapper -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Microblaze_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Microblaze_wrapper_utilization_synth.rpt -pb Microblaze_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
